title: Rynaard Burger's Blog
site.locale: en-GB
url: "https://rynaardb.com" # the base hostname & protocol for your site, e.g. http://example.com
search: true
paginate: 5
paginate_path: /page:num/

twitter:
  username: "rynaardb"

# Build settings
markdown: kramdown

remote_theme: "mmistakes/minimal-mistakes@4.15.1"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate

# Main
main:
  - title: "Posts"
    url: /year-archive/
  - title: "About"
    url: /about/

# Theme
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Author
author:
  name: "Rynaard Burger"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "I’m a Software Engineer based in Munich, Germany. Currently working as an iOS Engineer @ XING Events GmbH. I love building stuff and solving real-world problems."
  location: "Munich, DE"
  xing: Rynaard_Burger
  email: ryno.burger@gmail.com
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/rynaardb"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rynaardb"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/rynaardb/"

# Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/rynaardb"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rynaardb"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/rynaardb/"

# Google Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-4091617-7"
    anonymize_ip: false # default

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true