title: Rynaard Burger
site.locale: en-GB
url: "https://rynaardb.com" # the base hostname & protocol for your site, e.g. http://example.com
search: true
paginate: 5
paginate_path: /page:num/
logo: "/assets/images/logo.png"

twitter:
  username: "rynaardb"

# Build settings
markdown: kramdown

remote_theme: "rynaardb/minimal-mistakes"
# remote_theme: "jeffreytse/jekyll-theme-yat"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate

# Main
main:
  - title: "Posts"
    url: /year-archive/
  - title: "About"
    url: /about/

# Theme
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Author
author:
  name: "Rynaard Burger"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Hello, I am Rynaard Burger.<br/><br/> Things I do:<br/><br/>💻 Software Engineering<br/>📱 Systems Design<br/>🛠 Architecture<br/>☁️ Cloud Computing<br/><br/>🖥 [Things I use](https://rynaardb.com/uses)."
  location: "Munich, DE"
  xing: Rynaard_Burger
  email: ryno.burger@gmail.com
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/rynaardb"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rynaardb"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rynaardburger/"

# Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/rynaardb"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rynaardb"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rynaardburger/"

# Google Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-4091617-7"
    anonymize_ip: false # default

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
